[package]
name = "modular_webrust"
version = "0.1.0"
authors = ["Linggar Primahastoko <x@linggar.asia>"]

[dependencies]
nickel = "0.8.1"
rustc-serialize = "0.3.19"
mysql = "7.1.2"
pwhash = "0.1.1"
rust-ini = "0.9"
